"""Type stub file for cli.py."""

from datetime import datetime
import uuid
from typing import NoReturn

def get_current_username() -> str: ...
def handle_error(error: Exception, exit_code: int = 1) -> NoReturn: ...
def question_main() -> None: ...
def answer_main() -> None: ...
def thought_main() -> None: ... 